controllers/KeywordGroupsController.php
<?php

namespace app\controllers;

use app\modules\admin\controllers\KeywordsSearch;
use app\modules\admin\models\Keywords;
use app\modules\admin\models\ProjectSearch;
use Yii;
use app\modules\admin\models\KeywordGroups;
use app\modules\admin\controllers\KeywordGroupsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KeywordGroupsController implements the CRUD actions for KeywordGroups model.
 */
class KeywordGroupsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all KeywordGroups models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KeywordGroupsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['semantik'=> null]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single KeywordGroups model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionShow()
    {
        $status = Yii::$app->request->get('status');
        $searchModel = new KeywordGroupsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['status'=> $status]);
        $dataProvider->query->andWhere(['semantik'=> Yii::$app->user->getId()]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new KeywordGroups model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new KeywordGroups();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing KeywordGroups model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['keyword-groups/control','id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing KeywordGroups model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the KeywordGroups model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return KeywordGroups the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = KeywordGroups::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionWork()
    {
        if (Yii::$app->request->post('keylist')) {
            foreach(Yii::$app->request->post('keylist') as $id){
                $group = KeywordGroups::findOne(['id' => (int)$id]);
                $group->status = KeywordGroups::STATUS_V_RABOTE;
                $group->semantik = Yii::$app->user->id;
                $group->in_work =  date('Y-m-d H:i:s');
                $group->save(false);
            }
        }

        return 'Ключевики взялись на работу.';
    }

    public function actionControl($id)
    {
            $group = KeywordGroups::findOne(['id' => $id]);
            $keywords = Keywords::findAll(['group_id' => $group->connect_id]);
            $searchModel = new KeywordsSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            $dataProvider->query->andWhere(['group_id'=> $group->connect_id]);
            return $this->render('control', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'keywords' => $keywords,
                'model' => $group,
            ]);


    }

    public function actionCheck()
    {

        $post = Yii::$app->request->post('KeywordGroups');
      $model = KeywordGroups::findOne(['id' => $post['id']]);
      $model->add_keywords = $post['add_keywords'];
      $model->status++;
      $model->save();
        return $this->redirect(['keyword-groups/show','status' =>  $model->status]);


    }

    public function actionGroupProcess($id)
    {
        $group = KeywordGroups::findOne(['id' => $id]);
        $keywords = Keywords::findAll(['group_id' => $group->connect_id]);
        $searchModel = new KeywordsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['group_id'=> $group->connect_id]);
        return $this->render('group_process', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'keywords' => $keywords,
            'model' => $group,
        ]);
    }

    public function actionUsedGroup()
    {
        $status = KeywordGroups::STATUS_ISPOLZOVANNIE;
        $searchModel = new ProjectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('used_group', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'title' => KeywordGroups::getStatusName($status),
        ]);
    }

    public function actionGroup()
    {

     foreach ($_POST['keylist'] as $key){
           $model = Keywords::findOne(['id' => $key]);
           $model->group_id = $_POST['id'][0];
           $model->color = 0;
           $model->save();

           $old_group = KeywordGroups::findOne(['id' => $_POST['model']]);
           $old_group->frequency -= $model->frequency;
           $old_group->save();

           $new_group = KeywordGroups::findOne(['connect_id' => $_POST['id'][0]]);
           $new_group->project = $old_group->project;
           $new_group->frequency += $model->frequency;
           $new_group->save();
       }
        Yii::$app->getSession()->setFlash('success', 'Ключевики перешли  в другую группу');
        return true;
    }

    public function actionOffer()
    {
        $use = 1;
        $keywds = Keywords::find()->where(['group_id' => $_POST['id']])->all();
        foreach ($keywds as $keys){
            if($keys->color != 0 && $keys->color > $use){
                $use = $keys->color;
            }
        }
        $use++;
        if($use == 10){
            $use = 1;
        }
        foreach ($_POST['keylist'] as $key){
            $model = Keywords::findOne(['id' => $key]);
            $group = KeywordGroupsSearch::findOne(['connect_id' => $model->group_id]);
            $model->color = $use;
            $model->save();
        }
        Yii::$app->getSession()->setFlash('success', 'Успешно');
        return true;
    }

    public function actionNewGroup()
    {
        $newGroup = new KeywordGroups();
        $count = 0;
        if ($_POST) {
            $group_id = (new \yii\db\Query())
                ->select(['max(connect_id)'])
                ->from('keyword_groups')
                ->scalar();

            $color_count = (new \yii\db\Query())
                ->select(['color'])
                ->from('keyword_groups')
                ->orderBy(['id' => SORT_DESC])
                ->limit(1)
                ->scalar();

            $group_id += 11;
            $color_count++;
            if($color_count <= 10){
                $newGroup->color = $color_count;
            }else{
                $newGroup->color = 1;
            }

            $newGroup->name = $_POST['name'];
            $newGroup->status = KeywordGroups::STATUS_V_RABOTE;

            $newGroup->semantik = Yii::$app->user->getId();
            $newGroup->connect_id = $group_id;
            $newGroup->save();

            foreach ($_POST['keylist'] as $key){
                $count++;
                $model = Keywords::findOne(['id' => $key]);
                $model->group_id = $group_id;


                $old_group = KeywordGroups::findOne(['id' => $_POST['model']]);
                $old_group->frequency -= $model->frequency;
                $old_group->save();

                if($count == 1){

                    if((int)$model->frequency > 300){
                        $newGroup->import_key = 2;
                    }

                    if((int)$model->frequency <= 300){
                        $newGroup->import_key = 1;
                    }
                }

                $newGroup->project = $old_group->project;
                $newGroup->frequency += $model->frequency;
                $newGroup->save();
            }

views/keyword-groups/_form.php
<?php

use app\modules\admin\models\Project;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\KeywordGroups */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="keyword-groups-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="panel panel-default panel-body">

        <div class="row">

            <div class="col-md-4">
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="col-md-4">
    <?= $form->field($model, 'frequency')->textInput() ?>
            </div>
            <div class="col-md-12">
    <?= $form->field($model, 'add_keywords')->textArea(['maxlength' => true, 'rows' => 10])  ?>
            </div>
            <div class="col-md-4">
    <?php $projects = Project::find()->orderBy('name')->all(); ?>

    <?=
    $form->field($model, 'project')->widget(Select2::classname(), [
        'data' => ArrayHelper::Map($projects, 'id', 'name'),
        'options' => ['placeholder' => 'Выберите проект...'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>
            </div>

            <div class="col-md-4">
    <?= $form->field($model, 'status')->dropDownList($model->statuses); ?>
            </div>

            <div class="col-md-4">
    <?= $form->field($model, 'import_key')->dropDownList($model->importKey, ['prompt' => 'Выберите значение...']); ?>
            </div>
            </div>

    </div>
    <div class="form-group">
        <?= Html::submitButton('Создать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/keyword-groups/_form_update.php
<?php

use app\modules\admin\models\Project;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\KeywordGroups */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="keyword-groups-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="panel panel-default panel-body">

        <div class="row">

            <div class="col-md-4">
                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
            </div>


        </div>

    </div>
    <div class="form-group">
        <?= Html::submitButton('Создать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/keyword-groups/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\controllers\KeywordGroupsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="keyword-groups-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'semantik') ?>

    <?= $form->field($model, 'frequency') ?>

    <?= $form->field($model, 'add_keywords') ?>

    <?php // echo $form->field($model, 'project') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'import_key') ?>

    <?php // echo $form->field($model, 'in_work') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/keyword-groups/control.php
<?php

use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use rmrevin\yii\module\Comments;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\controllers\KeywordGroupsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = $model->name;
$p = \app\modules\admin\models\Project::findOne(['id' => $model->project]);
$this->params['breadcrumbs'][] = ['label' => 'Группы ключевиков', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $p->name];
$this->params['breadcrumbs'][] = ['label' => $model->getStatusName($model->status)];

?>
<br/>
<div class="keyword-groups-index">


    <p>
    </p>
    <div class="panel panel-default panel-body">
        <h1><?=$model->name;?> </h1>  <?= Html::a('Редактировать название', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <span class="btn btn-success" onClick="offer()">Предложить выделить</span>
        <span class="btn btn-danger" onClick="deleteKey()"><i class="fa fa-trash"></i> Удалить</span>
        <input type="hidden" id="color-ids" value="<?=$model->connect_id?>">
        <?php
        \yii\bootstrap\Modal::begin([
            'header' => 'Группы',
            'toggleButton' => ['label' => '<i class="fa fa-upload"></i> Переместить в другую групппу',
                'tag' => 'button',
                'class' => 'btn btn-info',],
        ]);
        ?>
        <div id="changeGroup">
            <?php $form = ActiveForm::begin(['action' => 'group']); ?>


            <?php $projects = \app\modules\admin\models\KeywordGroups::find()->orderBy('name')->all(); ?>
            <?= $form->field($model, 'id')->hiddenInput(['value'=> $model->id ])->label(false); ?>
            <?=
            $form->field($model, 'conn_id')->widget(Select2::classname(), [
                'data' => ArrayHelper::Map($projects, 'connect_id', 'name'),
                'options' => ['placeholder' => 'Название'],
                'pluginOptions' => [
                    'allowClear' => false,
                    'multiple' => true,
                ],
            ]);
            ?>



            <div class="form-group">
                <span class="btn btn-success" onClick="group()">Переместить</span>
                <span class="btn btn-info" onClick="toggleGroup()">Создать новую группу</span>
            </div>

            <?php ActiveForm::end(); ?>
        </div>

        <div id="newGroup" style="display: none;">
            <?php $form = ActiveForm::begin(['action' => 'group']); ?>


            <?php $projects = \app\modules\admin\models\KeywordGroups::find()->orderBy('name')->all(); ?>
            <?= $form->field($model, 'id')->hiddenInput(['value'=> $model->id ])->label(false); ?>
            <?= $form->field($model, 'conn_id')->hiddenInput(['value'=> $model->connect_id ])->label(false);?>
            <?= $form->field($model, 'name')->textInput(['maxlength' => true,'value' => '']) ?>



            <div class="form-group">
                <span class="btn btn-success" onClick="newGroup()">Создать</span>
                <span class="btn btn-info" onClick="toggleGroup2()">Выбрать из списка</span>
            </div>

            <?php ActiveForm::end(); ?>
        </div>


        <?php \yii\bootstrap\Modal::end(); ?>


        <p>
        </p>

        <?= GridView::widget([
            'id' => 'grid',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'rowOptions'=>function($model){
                if($model->color){
                    $code = \app\modules\admin\models\Colors::findOne(['id' => $model->color]);
                    return ['style' => 'background:'.$code->code];
                }
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'class' => 'yii\grid\CheckboxColumn',
                    'name' => 'checked',
                    'checkboxOptions' => function($model) {
                        return ['value' => $model->id];
                    },
                    'contentOptions' => ['style' => 'text-align:center;'],
                    'headerOptions' => ['style' => 'text-align:center;']
                ],
                [
                    'attribute' => 'keyword',
                    'filterInputOptions' => [
                        'class'       => 'form-control',
                        'placeholder' => 'Искать ключевик...'
                    ]
                ],
                [
                    'attribute' => 'frequency',
                    'filter' => false,
                ],
            ],
        ]); ?>



    </div>
    <?php $form = ActiveForm::begin(['action' => 'check']); ?>
    <div class="panel panel-default panel-body">


                <?= $form->field($model, 'id')->hiddenInput(['value'=> $model->id ])->label(false); ?>
                <?= $form->field($model, 'add_keywords')->textArea(['maxlength' => true, 'rows' => 10])  ?>

    </div>
    <div class="form-group">
        <?= Html::submitButton('Сдать на проверку', ['class' => 'btn btn-success']) ?>

    </div>

    <?php ActiveForm::end(); ?>
</div>

<?= Comments\widgets\CommentListWidget::widget([
    'entity' => (string)"group_id-{$model->id}", // type and id
]); ?>


<script type="text/javascript">

    function offer() {
        $('form').submit(function (e) {
            e.preventDefault();
        });
        var keys = $('#grid').yiiGridView('getSelectedRows');
        var id = $('#color-ids').val();
        console.log(id);
        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые Группы',
                confirmButtonColor: "#337ab7"
            });
            return;
        }
        var dialog = confirm('Выделить ?');
        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'offer',
                data: {keylist: keys,id:id},
                success: function (result) {
//                    swal({
//                        title: "",
//                        text: result,
//                        confirmButtonColor: "#337ab7"
//                    });
                    location.reload();
                }
            });
        }
    }
    function group() {
        $('form').submit(function (e) {
            e.preventDefault();
        });
        var keys = $('#grid').yiiGridView('getSelectedRows');
        var  id = $('#keywordgroups-conn_id').val();
        var model_id = $('#keywordgroups-id').val();

        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые Группы',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('Переместить в новую группу?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'group',
                data: {keylist: keys,id:id,model:model_id},
                success: function (result) {
//                    swal({
//                        title: "",
//                        text: result,
//                        confirmButtonColor: "#337ab7"
//                    });
                    location.reload();
                }
            });
        }
    }

    function newGroup() {
        $('form').submit(function (e) {
            e.preventDefault();
        });
        var keys = $('#grid').yiiGridView('getSelectedRows');
        var  id = $('#keywordgroups-conn_id').val();
        var model_id = $('#keywordgroups-id').val();
        var name = $('#keywordgroups-name').val();

        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые Группы',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('Создать новую группу?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'new-group',
                data: {keylist: keys,id:id,model:model_id,name:name},
                success: function (result) {
//                    swal({
//                        title: "",
//                        text: result,
//                        confirmButtonColor: "#337ab7"
//                    });
                    location.reload();
                }
            });
        }
    }

    function toggleGroup() {
        var x = document.getElementById("changeGroup");
        var b = document.getElementById("newGroup");
        x.style.display = "none";
        b.style.display = "block";

    }

    function toggleGroup2() {
        var x = document.getElementById("changeGroup");
        var b = document.getElementById("newGroup");
        x.style.display = "block";
        b.style.display = "none";
    }

    function deleteKey() {

        var keys = $('#grid').yiiGridView('getSelectedRows');


        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые ключевики',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('точно Удалить?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'delete-key',
                data: {keylist: keys},
                success: function (result) {
//                    swal({
//                        title: "",
//                        text: result,
//                        confirmButtonColor: "#337ab7"
//                    });
                    location.reload();
                }
            });
        }
    }

</script>

views/keyword-groups/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\KeywordGroups */

$this->title = 'Создать группу ключевиков';
$this->params['breadcrumbs'][] = ['label' => 'Группы ключевиков', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="keyword-groups-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/keyword-groups/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\controllers\KeywordGroupsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Группы ключевиков';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="keyword-groups-index">
    <?= Yii::$app->session->getFlash('error'); ?>

    <p>
    </p>
    <div class="panel panel-default panel-body">

    <?php Pjax::begin(['id' => 'pjax_grid']); ?>
        <?php if(!isset($_GET['status'])):?>
             <span class="btn btn-success" onClick="group()">Взять в работу</span>
        <?php endif;?>
        <p>
        </p>

    <?= GridView::widget([
            'id' => 'grid',
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'class' => 'yii\grid\CheckboxColumn',
                'name' => 'checked',
                'checkboxOptions' => function($model) {
                    return ['value' => $model->id];
                },
                'contentOptions' => ['style' => 'text-align:center;'],
                'headerOptions' => ['style' => 'text-align:center;']
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function ($data) {
                        if($data->status == \app\modules\admin\models\KeywordGroups::STATUS_V_RABOTE)
                            return Html::a($data->name, ['keyword-groups/control', 'id' => $data->id]);



                    return Html::a($data->name, ['keyword-groups/group-process', 'id' => $data->id]);
                },
                'contentOptions' => ['style' => 'text-align:center white-space: nowrap;;'],

            ],
            [
                'attribute' => 'semantik',
                'content' => function($model){
                  return isset($model->semantik) ? "<span style='color:green'>".$model->getUserName($model->semantik)."</span>" : '<span style="color:red">Свободен</span>';

                },
                'contentOptions' => ['style' => 'text-align:center white-space: nowrap;;'],
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'prompt' => 'Все',
                ],
                'filter'=> \app\modules\admin\models\KeywordGroups::GetUsers(),

            ],
            'frequency',
            [
                'attribute' => 'project',
                'value' => function($searchModel){
                    $project = \app\modules\admin\models\Project::findOne(['id' => $searchModel->project]);
                    return $project->name;
                },
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'prompt' => 'Все',
                ],
                'filter'=> \app\modules\admin\models\KeywordGroups::GetProjects(),

            ],
            [
                'attribute' => 'status',
                'value' => function($searchModel){
                    $a = \app\modules\admin\models\KeywordGroups::getStatusesLabel();
                    return $a[$searchModel->status];
                },
                'filter' => false,

            ],
            [
                'attribute' => 'in_work',
                'value' => function($model){

                    return isset($model->in_work) ? date("d.m.Y", strtotime($model->in_work)) : '';
                },
                'filter' => false,

            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>
</div>


<script type="text/javascript">


    function group() {

        var keys = $('#grid').yiiGridView('getSelectedRows');

        if (keys == '') {
            swal({
                title: "",
                text: 'Отметьте флажками необходимые Группы',
                confirmButtonColor: "#337ab7"
            });
            return;
        }

        var dialog = confirm('Взять в работу?');

        if (dialog == true) {

            $.ajax({
                type: "POST",
                url: 'work',
                data: {keylist: keys},
                success: function (result) {
                    swal({
                        title: "",
                        text: result,
                        confirmButtonColor: "#337ab7"
                    });
                    $.pjax.reload({container: '#pjax_grid'});
                }
            });
        }
    }


</script>

views/keyword-groups/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\KeywordGroups */

$this->title =  $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Группы ключевиков', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="keyword-groups-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_update', [
        'model' => $model,
    ]) ?>

</div>

views/keyword-groups/used_group.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\ProjectSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="project-index">

    <h1><?= Html::encode($title) ?></h1>

    <p></p>
    <div class="panel panel-default panel-body">


        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                [
                    'attribute' => 'name',
                    'format' => 'raw',
                    'filter' => false,

                ],
                [
                    'attribute' => 'count_used',
                    'value' => function ($model) {

                        return $model->getCountUsedGroups() ." / ". $model->allowed_groups;

                    },
                    'format' => 'raw',
                    'contentOptions' => ['style' => 'width: 10%; white-space: nowrap;'],
                ],
            ],
        ]); ?>


    </div>
</div>

views/keyword-groups/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\KeywordGroups */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Группы ключевиков', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="keyword-groups-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'semantik',
            'frequency',
            'add_keywords',
            'project',
            'status',
            'import_key',
            'in_work',
        ],
    ]) ?>

</div>